services:

    #
    # External
    #
    gearman.external.finder:
        class: %gearman.external.finder.class%

    #
    # Generators
    #
    gearman.unique_job_identifier:
        class: %gearman.unique_job_identifier.class%
        arguments:
            generate_unique_key: %gearman.default.settings.generate_unique_key%

    #
    # Dispatchers
    #
    gearman.dispatcher.abstract:
        abstract: true
        arguments:
            event.dispatcher: @event_dispatcher

    gearman.dispatcher.callbacks:
        parent: gearman.dispatcher.abstract
        class: %gearman.dispatcher.callbacks.class%

    #
    # Services
    #
    gearman.parser:
        class: %gearman.parser.class%
        arguments:
            kernel: @kernel
            annotations_reader: @annotation_reader
            gearman_finder: @gearman.external.finder
            gearman_bundles: %gearman.bundles%
            gearman_servers: %gearman.servers%
            gearman_default_settings: %gearman.default.settings%

    gearman.cache.wrapper:
        class: %gearman.cache.wrapper.class%
        arguments:
            gearman_parser: @gearman.parser
            gearman_cache: @liip_doctrine_cache.ns.gearman
            gearman_cache_id: %gearman.cache.id%
        calls:
            - [load,  [@liip_doctrine_cache.ns.gearman, %gearman.cache.id%]]
        tags:
            - { name: kernel.cache_clearer }
            - { name: kernel.cache_warmer, priority: 0 }

    gearman.describer:
        class: %gearman.describer.class%
        arguments:
            kernel: @kernel

    gearman.abstract.service:
        abstract:  true
        arguments:
            gearman_cache_wrapper: @gearman.cache.wrapper
            default_settings: %gearman.default.settings%

    gearman.execute:
        class: %gearman.execute.class%
        parent: gearman.abstract.service
        calls:
            - [setContainer,  [@service_container]]
            - [setEventDispatcher, [@event_dispatcher]]

    gearman:
        class: %gearman.client.class%
        parent: gearman.abstract.service
        calls:
            - [initTaskStructure, []]
            - [setDefaultServers, [%gearman.servers%]]
            - [setGearmanCallbacksDispatcher, [@gearman.dispatcher.callbacks]]
            - [setUniqueJobIdentifierGenerator, [@gearman.unique_job_identifier]]
            - [setDefaultSettings, [%gearman.default.settings%]]